"""create_document_chunks_table

Revision ID: db13c1a5020d
Revises: 5784b87a58c2
Create Date: 2026-07-27 01:35:48.061749

"""
from collections.abc import Sequence

import pgvector.sqlalchemy  # <-- ДОДАНО ІМПОРТ
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'db13c1a5020d'
down_revision: str | Sequence[str] | None = '5784b87a58c2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # <-- ДОДАНО СТВОРЕННЯ РОЗШИРЕННЯ В БД
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_source'), 'document_chunks', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_chunks_source'), table_name='document_chunks')
    op.drop_table('document_chunks')
    # ### end Alembic commands ###